server:
  port: 8080

spring:
  application:
    name: 316space-be
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

jwt:
  secret: ${JWT_SECRET:dev-secret-key-change-in-production-must-be-256bits}
  expiration-ms: 1800000 # 30분
